version: '3.8'

services:
  code-server:
    image: linuxserver/code-server
    container_name: code-server
    hostname: code-server
    restart: unless-stopped
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Dhaka
    ports:
      - 8443:8443
    networks:
      - code-server

networks:
  code-server:
